name: Build and deploy ASP.NET Web Forms app to Azure

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore WebApplication5.sln

      - name: Build with MSBuild
        run: msbuild WebApplication5.sln /p:Configuration=Release

      - name: Publish using MSBuild
        run: msbuild WebApplication5.sln /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Configuration=Release /p:PublishDir=".\publish\"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-app-service-name>
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .\publish
